# Generated by Django 5.1 on 2024-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='color',
            field=models.CharField(choices=[('green', '#025A4E'), ('cream', '#EDE7DE')], max_length=50),
        ),
    ]
