# Generated by Django 5.1 on 2024-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=255)),
                ('preview_url', models.URLField(max_length=500)),
                ('stack_use', models.CharField(max_length=500)),
                ('github_url', models.URLField(max_length=500)),
                ('color', models.CharField(choices=[('#025A4E', 'green'), ('#EDE7DE', 'cream')], max_length=50)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
