# Generated by Django 5.1 on 2024-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
