# Generated by Django 5.1 on 2024-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_project_github_url_alter_project_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
